## Config file

# Log 
seed: 777
use_cuda: 1           # 1 for True, 0 for False

# dataset
#### from scrach with clip loss
speaker_no: 2
mix_lst_path: ./data/KUL/mixture_data_list_2mix.csv
audio_direc: /data/sriyar/KUL_eeg/audio_8k/
reference_direc: /data/sriyar/KUL_eeg/eeg/
audio_sr: 8000
ref_sr: 128         # reference sampleing rate, lip: 25 , gesture: 15, eeg: 128

# dataloader
num_workers: 8
batch_size: 4         # 2-GPU training with a total effective batch size of 8
accu_grad: 1
effec_batch_size: 12   # per GPU, only used if accu_grad is set to 1, must be multiple times of batch size
max_length: 10        # truncate the utterances in dataloader, in seconds 

# network settings
init_from: None       # 'None' or a log name 'log_2024-07-22(18:12:13)'
causal: 0             # 1 for True, 0 for False
network_reference:
  cue: eeg            # lip or speech or gesture or EEG
network_audio:
  backbone: neuroheed
  N: 256
  L: 20
  B: 64
  H: 128
  K: 100
  R: 6

# optimizer
loss_type: sisdr      # "snr", "sisdr", "hybrid"
init_learning_rate: 0.000125
lr_warmup: 1          # 1 for True, 0 for False
max_epoch: 100
clip_grad_norm: 5
W0514 11:06:43.407000 3925381 site-packages/torch/distributed/run.py:792] 
W0514 11:06:43.407000 3925381 site-packages/torch/distributed/run.py:792] *****************************************
W0514 11:06:43.407000 3925381 site-packages/torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0514 11:06:43.407000 3925381 site-packages/torch/distributed/run.py:792] *****************************************
Traceback (most recent call last):
  File "/home/sriyar/neuroheed/ClearerVoice-Studio/train/target_speaker_extraction/train.py", line 1, in <module>
    import yamlargparse, os, random
ModuleNotFoundError: No module named 'yamlargparse'
Traceback (most recent call last):
  File "/home/sriyar/neuroheed/ClearerVoice-Studio/train/target_speaker_extraction/train.py", line 1, in <module>
    import yamlargparse, os, random
ModuleNotFoundError: No module named 'yamlargparse'
Traceback (most recent call last):
  File "/home/sriyar/neuroheed/ClearerVoice-Studio/train/target_speaker_extraction/train.py", line 1, in <module>
    import yamlargparse, os, random
ModuleNotFoundError: No module named 'yamlargparse'
E0514 11:06:43.525000 3925381 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 3925468) of binary: /home/sriyar/miniconda3/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/sriyar/miniconda3/lib/python3.12/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/home/sriyar/miniconda3/lib/python3.12/site-packages/typing_extensions.py", line 2853, in wrapper
    return arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/sriyar/miniconda3/lib/python3.12/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/home/sriyar/miniconda3/lib/python3.12/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/home/sriyar/miniconda3/lib/python3.12/site-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/home/sriyar/miniconda3/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sriyar/miniconda3/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-05-14_11:06:43
  host      : ailab-3080ti
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3925469)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-05-14_11:06:43
  host      : ailab-3080ti
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3925470)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-14_11:06:43
  host      : ailab-3080ti
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3925468)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
